### ISSUE TITLE
disable warning logs from polkadotjs

### ISSUE THREAD

**Issue by frankiebee** [entropyxyz/sdk#303]
disable warning logs from polkadotjs

**Comment by mixmix** [comment]
done

**Comment by frankiebee** [comment]
i'm still seeing this in the cli 
found this: https://github.com/polkadot-js/api/blob/0bfa069f1b02d788ea619b84e4987402ef0c51fa/packages/api/src/types/index.ts#L69C3-L69C13 gonna try it when we init substrate api
